### ISSUE TITLE
执行execute返回的ExecutionResponse怎么解析? 

### ISSUE THREAD

**Issue by sessionboy** [bk-rs/nebula-rs#1]
ExecutionResponse这个是thrift自动生成的吗？
```rust
#[derive(Clone, Debug, PartialEq)]
    pub struct ExecutionResponse {
        pub error_code: crate::types::ErrorCode,
        pub latency_in_us: ::std::primitive::i32,
        pub data: ::std::option::Option<common::types::DataSet>,
        pub space_name: ::std::option::Option<::std::vec::Vec<::std::primitive::u8>>,
        pub error_msg: ::std::option::Option<::std::vec::Vec<::std::primitive::u8>>,
        pub plan_desc: ::std::option::Option<crate::types::PlanDescription>,
        pub comment: ::std::option::Option<::std::vec::Vec<::std::primitive::u8>>,
    }
```
```rust
ExecutionResponse { 
   error_code: ErrorCode::E_SYNTAX_ERROR,  
   latency_in_us: 108, 
   data: None, 
   space_name: Some([]), 
   error_msg: Some([83, 121, 110, 116, 97, 120, 69, 114, 114, 111, 114, 58, 32, 115, 121, 110, 116, 97, 120, 32, 101, 114, 114, 111, 
   114, 32, 110, 101, 97, 114, 32, 96, 72, 79, 83, 84, 83, 115, 115, 39]), 
   plan_desc: None, 
   comment: None 
}
```
它没有实现Deserialize，返回的是&[u8]，怎么解析它？

**Comment by vkill** [comment]
> ExecutionResponse这个是thrift自动生成的吗？
Yes

> 它没有实现Deserialize，返回的是&[u8]，怎么解析它？
WIP

**Comment by sessionboy** [comment]
老哥，改进一下发个版本呗，我想用这个库。
如果能做成一个orm那就更棒了。

**Comment by vkill** [comment]
The serde [example](https://github.com/bk-rs/nebula-rs/blob/master/demos/async-std/src/graph_crud.rs#L87-L105)

**Comment by sessionboy** [comment]
很棒👍。就是稍微有点繁琐。
我建议返回serde_json的Value或许会更好，可以直接访问，可以增删改，也可以直接返回给客户端，也可以很方便地转换成其他类型，处理起来很灵活。

**Comment by vkill** [comment]
> 我建议返回serde_json的Value或许会更好

这个和 json 没有关系的嘛，且也根本不会有那么繁琐的数据类型，可以看这里 https://docs.nebula-graph.com.cn/manual-CN/2.query-language/1.data-types/data-types/

> 可以直接访问，可以增删改，也可以直接返回给客户端，也可以很方便地转换成其他类型，处理起来很灵活。

目前这个受限在哪里呢？贴段代码上来呢？

**Comment by sessionboy** [comment]
```rust
#[derive(Deserialize, Debug)]
    struct Foo {
        #[serde(rename(deserialize = "VertexID"))]
        vid: u64,
        #[serde(rename(deserialize = "FOO.field_string"))]
        field_string: String,
        #[serde(rename(deserialize = "FOO.field_int"))]
        field_int: u64,
        #[serde(rename(deserialize = "FOO.field_double"))]
        field_double: f64,
        #[serde(rename(deserialize = "FOO.field_bool"))]
        field_bool: bool,
        #[serde(rename(deserialize = "FOO.field_timestamp"), with = "ts_seconds")]
        field_timestamp: DateTime<Utc>,
    }
    let foo = session
        .query_as::<Foo>(&format!(r#"LOOKUP ON {tag_name} WHERE {tag_name}.field_string == "1" YIELD {tag_name}.field_string, {tag_name}.field_int, {tag_name}.field_double, {tag_name}.field_bool, {tag_name}.field_timestamp"#, tag_name = tag_name))
        .await
        .unwrap();
```
每个字段都需要这样去声明一遍，是稍微有点繁琐的。

> 目前这个受限在哪里呢？贴段代码上来呢？

根据我的经验，大部分查询结果都是会直接返回给客户端的，一部分会用来处理其他逻辑的，这时候如果查询结果是json的话就很好处理了，可以直接返回给客户端，也可以做其他逻辑处理，而不需要声明一堆类型然后再serde转换，最后才能做其他处理。

或者你可以写两个接口嘛(query、query_json)，一个像上面那样需要serde转换的，另一个不需要serde转换，直接返回json的。

主要是为了更方便啦，目前这样其实也可以。

**Comment by sessionboy** [comment]
有没有计划做成 orm ?  提供建模，CURD、订阅、缓存等功能，要是这样那就更棒了。我有想过自己写一个的，可是没有时间。

**Comment by vkill** [comment]
> 每个字段都需要这样去声明一遍

本来就应该这样，用 sqlx 的时候不也这样

> 或者你可以写两个接口嘛(query、query_json)

没有必要的，这个地方和 json 完全没有关系。如果需要也得是 `let foo = session
        .query_as::<serde_json::Value>(&format!(r#"LOOKUP ON {tag_name} WHERE {tag_name}.field_string == "1" YIELD {tag_name}.field_string"#, tag_name = tag_name))
        .await?;` 这样去使用，不过目前并不支持

**Comment by vkill** [comment]
> 有没有计划做成 orm

没有计划。sqlx 不也没有 orm 吗？且图数据库本来就小众，开发 orm 又不是个简单的活
